allow passing manifest file to rust setup

diff --git a/.github/actions/setup-rust/action.yml b/.github/actions/setup-rust/action.yml
--- a/.github/actions/setup-rust/action.yml
+++ b/.github/actions/setup-rust/action.yml
@@ -5,6 +5,10 @@ inputs:
   version:
     description: "The toolchain version string to pass to 'rustup' (e.g. 1.68.2 or nightly)."
     required: true
+  manifest-file:
+    description: "Parse the rust version from the provided 'Cargo.toml' manifest file."
+    required: false
+    default: ""
   profile:
     description: "Specify a 'rustup' profile during installation."
     required: false
@@ -36,10 +40,32 @@ outputs:
 runs:
   using: "composite"
   steps:
+    - uses: "./.github/actions/parse-rust-version"
+      if: inputs.manifest-file != ""
+      id: parse-config
+      with:
+        manifest: inputs.manifest-file
+        strict: true
+
     - name: Install rust (stable)
       shell: bash
       run: |
-        CMD=("rustup toolchain install ${{ inputs.version }}")
+        VERSION="${{ inputs.version }}"
+        if [[ ! -z "${{ inputs.manifest-file }}" ]]; then
+          if [[ ! -z "${{ inputs.version }}" ]]; then
+            echo "cannot specify both 'version' and 'manifest-file'"
+            exit 1
+          fi
+
+          VERSION="${{ steps.parse-config.outputs.version }}"
+        fi
+
+        if [[ -z "$VERSION" ]]; then
+          echo "missing Rust version; specify either 'version' or 'manifest-file'"
+          exit 1
+        fi
+
+        CMD=("rustup toolchain install $VERSION")
 
         CMD+=("--allow-downgrade")
         CMD+=("--no-self-update")
