fix(ci): simplify installation check step

diff --git a/.github/actions/setup-gdpack/action.yml b/.github/actions/setup-gdpack/action.yml
--- a/.github/actions/setup-gdpack/action.yml
+++ b/.github/actions/setup-gdpack/action.yml
@@ -58,7 +58,7 @@ runs:
     - name: Validate that the 'gdpack' executable was installed
       shell: bash
       run: |
-        if command -v gdpack [[ "$(${{ inputs.install-dir }}/bin/gdpack --version)" != "gdpack ${{ inputs.version }}" ]]; then
-          echo "Failed to install 'gdpack@v${{ inputs.version }}'!"
+        if ! command -v gdpack >/dev/null; then
+          echo "Failed to install 'gdpack'!"
           exit 1
         fi
